---
title: "Question 8 - Pay Grade"
output:
    word_document:
        fig_width: 10
        fig_height: 6
---

```{r, message = F, warning = F, echo = F}
library(here)
library(dplyr)
library(readr)
library(purrr)
library(tidyr)
library(stringr)
library(ggplot2)
library(forcats)
library(knitr)
opts_chunk$set(echo = F)
```

```{r, message = F}
surveyClean <-
    read_csv(here("data", "surveyClean.csv")) %>%
    mutate(payGrade = as.character(payGrade))

surveyQuestions <- read_csv(here("data", "surveyQs.csv"))
```

## Question 8 - What is your pay grade (Half Time)?

```{r}
surveyClean %>% 
    filter(!is.na(payGrade)) %>% {
    ggplot(., aes(payGrade)) +
    geom_bar(aes(y = ..count.. / sum(..count..))) +
    labs(title = "What is your pay grade (Half Time students)?",
         y = paste0("Proportion of Respondents (N = ", nrow(.), ")"),
         x = "Gross Monthly Pay") +
    coord_flip() +
    theme_bw() +
    theme(text = element_text(size = 20))}
```

## Question 8 - What is your pay grade (Half Time)?

```{r}
surveyClean %>% 
    filter(!is.na(payGrade)) %>% {
        ggplot(., aes(as.numeric(payGrade))) +
            geom_histogram(bins = 5, aes(y = stat(width * density))) +
            labs(title = "What is your pay grade (Half Time students)?",
                 y = paste0("Proportion of Respondents (N = ", nrow(.), ")"),
                 x = "Gross Monthly Pay") +
        theme_bw() +
        theme(text = element_text(size = 20))}
```

### Question 8 - Broken down by groups

```{r}
PlotByGroup <- function(df, groupVar, outcomeVar, title, xaxis) {
    
    df <- 
        df %>%
        filter(!is.na(.data[[outcomeVar]])) %>%
        count(.data[[groupVar]], .data[[outcomeVar]]) %>%
        group_by(.data[[groupVar]]) %>%
        mutate(prcnt = n / sum(n)) %>%
        filter(!is.na(.data[[groupVar]])) %>%
        mutate({{groupVar}} := paste0(.data[[groupVar]], " (N = ", sum(n), ")")) %>%
        ungroup()
    
    ggplot(df, aes(x = .data[[outcomeVar]], y = prcnt)) +
        geom_bar(stat = "identity") +
        theme_bw() +
        labs(title = title,
             y = "Proportion of Respondents",
             x = xaxis) +
        facet_wrap(~ .data[[groupVar]], nrow = 1) +
        coord_flip() +
        theme(text = element_text(size = 20),
              title = element_text(size = 17),
              strip.text.x = element_text(size = 10))
}

groupVars <- c("gender", "raceBinary", "race", "studentStatus", "college")
outcomeVars <- rep("payGrade", length(groupVars))
titles <- c("What is your pay grade (Half Time students)? - By gender",
            "What is your pay grade (Half Time students)? - By race",
            "What is your pay grade (Half Time students)? - By race",
            "What is your pay grade (Half Time students)? - By immigration status",
            "What is your pay grade (Half Time students)? - By college")

pmap(list(groupVars, outcomeVars, titles),
     PlotByGroup,
     df = surveyClean,
     xaxis = "Gross Monthly Pay")
```

### Question 8 - Broken down by groups

```{r}
PlotByGroupH <- function(df, groupVar, outcomeVar, title, xaxis) {
    
    df <- 
        df %>%
        filter(!is.na(.data[[outcomeVar]])) %>%
        count(.data[[groupVar]], .data[[outcomeVar]]) %>%
        group_by(.data[[groupVar]]) %>%
        mutate(prcnt = n / sum(n)) %>%
        filter(!is.na(.data[[groupVar]])) %>%
        mutate({{groupVar}} := paste0(.data[[groupVar]], " (N = ", sum(n), ")")) %>%
        ungroup()
    
    ggplot(df, aes(x = as.numeric(.data[[outcomeVar]]), y = prcnt)) +
        geom_histogram(bins = 5, aes(y = stat(width * density))) +
        theme_bw() +
        labs(title = title,
             y = "Proportion of Respondents",
             x = xaxis) +
        facet_wrap(~ .data[[groupVar]], nrow = 1) +
        coord_flip() +
        theme(text = element_text(size = 20),
              title = element_text(size = 17),
              strip.text.x = element_text(size = 10))
}

pmap(list(groupVars, outcomeVars, titles),
     PlotByGroupH,
     df = surveyClean,
     xaxis = "Gross Monthly Pay")
```
